/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthPathnameImport } from './routes/auth/$pathname'
import { Route as AuthSettingsRouteImport } from './routes/_auth.settings/route'
import { Route as AuthSettingsUsageImport } from './routes/_auth.settings/usage'
import { Route as AuthSettingsBillingImport } from './routes/_auth.settings/billing'
import { Route as AuthSettingsAccountImport } from './routes/_auth.settings/account'
import { Route as AuthAuthDeviceLinkImport } from './routes/_auth.auth/device-link'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthPathnameRoute = AuthPathnameImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRoute,
} as any)

const AuthSettingsRouteRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSettingsUsageRoute = AuthSettingsUsageImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)

const AuthSettingsBillingRoute = AuthSettingsBillingImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)

const AuthSettingsAccountRoute = AuthSettingsAccountImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)

const AuthAuthDeviceLinkRoute = AuthAuthDeviceLinkImport.update({
  id: '/auth/device-link',
  path: '/auth/device-link',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthImport
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameImport
      parentRoute: typeof rootRoute
    }
    '/_auth/auth/device-link': {
      id: '/_auth/auth/device-link'
      path: '/auth/device-link'
      fullPath: '/auth/device-link'
      preLoaderRoute: typeof AuthAuthDeviceLinkImport
      parentRoute: typeof AuthImport
    }
    '/_auth/settings/account': {
      id: '/_auth/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthSettingsAccountImport
      parentRoute: typeof AuthSettingsRouteImport
    }
    '/_auth/settings/billing': {
      id: '/_auth/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthSettingsBillingImport
      parentRoute: typeof AuthSettingsRouteImport
    }
    '/_auth/settings/usage': {
      id: '/_auth/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof AuthSettingsUsageImport
      parentRoute: typeof AuthSettingsRouteImport
    }
  }
}

// Create and export the route tree

interface AuthSettingsRouteRouteChildren {
  AuthSettingsAccountRoute: typeof AuthSettingsAccountRoute
  AuthSettingsBillingRoute: typeof AuthSettingsBillingRoute
  AuthSettingsUsageRoute: typeof AuthSettingsUsageRoute
}

const AuthSettingsRouteRouteChildren: AuthSettingsRouteRouteChildren = {
  AuthSettingsAccountRoute: AuthSettingsAccountRoute,
  AuthSettingsBillingRoute: AuthSettingsBillingRoute,
  AuthSettingsUsageRoute: AuthSettingsUsageRoute,
}

const AuthSettingsRouteRouteWithChildren =
  AuthSettingsRouteRoute._addFileChildren(AuthSettingsRouteRouteChildren)

interface AuthRouteChildren {
  AuthSettingsRouteRoute: typeof AuthSettingsRouteRouteWithChildren
  AuthAuthDeviceLinkRoute: typeof AuthAuthDeviceLinkRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSettingsRouteRoute: AuthSettingsRouteRouteWithChildren,
  AuthAuthDeviceLinkRoute: AuthAuthDeviceLinkRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/settings': typeof AuthSettingsRouteRouteWithChildren
  '/auth/$pathname': typeof AuthPathnameRoute
  '/auth/device-link': typeof AuthAuthDeviceLinkRoute
  '/settings/account': typeof AuthSettingsAccountRoute
  '/settings/billing': typeof AuthSettingsBillingRoute
  '/settings/usage': typeof AuthSettingsUsageRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/settings': typeof AuthSettingsRouteRouteWithChildren
  '/auth/$pathname': typeof AuthPathnameRoute
  '/auth/device-link': typeof AuthAuthDeviceLinkRoute
  '/settings/account': typeof AuthSettingsAccountRoute
  '/settings/billing': typeof AuthSettingsBillingRoute
  '/settings/usage': typeof AuthSettingsUsageRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/settings': typeof AuthSettingsRouteRouteWithChildren
  '/auth/$pathname': typeof AuthPathnameRoute
  '/_auth/auth/device-link': typeof AuthAuthDeviceLinkRoute
  '/_auth/settings/account': typeof AuthSettingsAccountRoute
  '/_auth/settings/billing': typeof AuthSettingsBillingRoute
  '/_auth/settings/usage': typeof AuthSettingsUsageRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/settings'
    | '/auth/$pathname'
    | '/auth/device-link'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/usage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/settings'
    | '/auth/$pathname'
    | '/auth/device-link'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/usage'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/settings'
    | '/auth/$pathname'
    | '/_auth/auth/device-link'
    | '/_auth/settings/account'
    | '/_auth/settings/billing'
    | '/_auth/settings/usage'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthPathnameRoute: typeof AuthPathnameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthPathnameRoute: AuthPathnameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/auth/$pathname"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/settings",
        "/_auth/auth/device-link"
      ]
    },
    "/_auth/settings": {
      "filePath": "_auth.settings/route.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/settings/account",
        "/_auth/settings/billing",
        "/_auth/settings/usage"
      ]
    },
    "/auth/$pathname": {
      "filePath": "auth/$pathname.tsx"
    },
    "/_auth/auth/device-link": {
      "filePath": "_auth.auth/device-link.tsx",
      "parent": "/_auth"
    },
    "/_auth/settings/account": {
      "filePath": "_auth.settings/account.tsx",
      "parent": "/_auth/settings"
    },
    "/_auth/settings/billing": {
      "filePath": "_auth.settings/billing.tsx",
      "parent": "/_auth/settings"
    },
    "/_auth/settings/usage": {
      "filePath": "_auth.settings/usage.tsx",
      "parent": "/_auth/settings"
    }
  }
}
ROUTE_MANIFEST_END */
